[package]
name = "spass"
version = "2.0.0"
authors = ["Sean Purcell <me@seanp.xyz>"]

[dependencies]
clap = "2.29.0"
rpassword = "2.0.0"
shellexpand = "1.0.0"
sodiumoxide = "0.0.16"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]
