[package]
name = "spass"
version = "2.0.0"
authors = ["Sean Purcell <me@seanp.xyz>"]

[dependencies]
bincode = "0.9.2"
clap = "2.29.0"
rpassword = "2.0.0"
serde = "1"
serde_derive = "1"
sodiumoxide = "0.0.16"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]
