[package]
name = "spass"
version = "2.1.0"
authors = ["Sean Purcell <me@seanp.xyz>"]

[dependencies]
clap = "2.29"
rpassword = "2.0"
shellexpand = "1.0"
sodiumoxide = "0.2"

[dependencies.rusqlite]
version = "0.23"
features = ["bundled"]
